<?xml version="1.0" encoding="utf-8"?>
<Database Name="RedBlood_DB" Class="RedBloodDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\RedBlood_DB.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RedBlood_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_UserProfiles" Member="aspnet_UserProfiles">
    <Type Name="aspnet_UserProfile">
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="aspnet_User_aspnet_UserProfile" Member="aspnet_User" ThisKey="UserID" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_UserProfile" Member="aspnet_UserProfile" ThisKey="UserId" OtherKey="UserID" Type="aspnet_UserProfile" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="aspnet_Memberships">
    <Type Name="aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CompanyContactPerson" Member="CompanyContactPersons">
    <Type Name="CompanyContactPerson">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CompanyLocationID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sex" Member="Sexes">
    <Type Name="Sex">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Sex_People" Member="Peoples" ThisKey="ID" OtherKey="SexID" Type="People" />
    </Type>
  </Table>
  <Table Name="dbo.Geo" Member="Geos">
    <Type Name="Geo">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FullnameNoDiacritics" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Geo_Geo" Member="Geos" ThisKey="ID" OtherKey="ParentID" Type="Geo" />
      <Association Name="Geo_People" Member="PeopleMailingGeo1" Storage="_Peoples" ThisKey="ID" OtherKey="MailingGeoID1" Type="People" />
      <Association Name="Geo_People1" Member="PeopleMailingGeo2" Storage="_Peoples1" ThisKey="ID" OtherKey="MailingGeoID2" Type="People" />
      <Association Name="Geo_People2" Member="PeopleMailingGeo3" Storage="_Peoples2" ThisKey="ID" OtherKey="MailingGeoID3" Type="People" />
      <Association Name="Geo_People3" Member="PeopleResidentGeo1" Storage="_Peoples3" ThisKey="ID" OtherKey="ResidentGeoID1" Type="People" />
      <Association Name="Geo_People4" Member="PeopleResidentGeo2" Storage="_Peoples4" ThisKey="ID" OtherKey="ResidentGeoID2" Type="People" />
      <Association Name="Geo_People5" Member="PeopleResidentGeo3" Storage="_Peoples5" ThisKey="ID" OtherKey="ResidentGeoID3" Type="People" />
      <Association Name="Geo_Org" Member="OrgsByGeo1" ThisKey="ID" OtherKey="GeoID1" Type="Org" />
      <Association Name="Geo_Org1" Member="OrgsByGeo2" ThisKey="ID" OtherKey="GeoID2" Type="Org" />
      <Association Name="Geo_Org2" Member="OrgsByGeo3" ThisKey="ID" OtherKey="GeoID3" Type="Org" />
      <Association Name="Geo_Geo" Member="ParentGeo" Storage="_Geo1" ThisKey="ParentID" OtherKey="ID" Type="Geo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Hospital" Member="Hospitals">
    <Type Name="Hospital">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NameInEnglish" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Hospital_Department" Member="Departments" ThisKey="ID" OtherKey="HospitalID" Type="Department" />
    </Type>
  </Table>
  <Table Name="dbo.TestDef" Member="TestDefs">
    <Type Name="TestDef">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TestDef_TestDef" Member="Children" ThisKey="ID" OtherKey="ParentID" Type="TestDef" />
      <Association Name="TestDef_Campaign" Member="CampaignsBySource" ThisKey="ID" OtherKey="SourceID" Type="Campaign" />
      <Association Name="TestDef_TestDef" Member="Parent" ThisKey="ParentID" OtherKey="ID" Type="TestDef" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.People" Member="Peoples">
    <Type Name="People">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Codabar" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SexID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Job" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResidentAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ResidentGeoID1" Storage="_ResidentGeo1" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ResidentGeoID2" Storage="_ResidentGeo2" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ResidentGeoID3" Storage="_ResidentGeo3" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="MailingAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MailingGeoID1" Storage="_MailingGeo1" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="MailingGeoID2" Storage="_MailingGeo2" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="MailingGeoID3" Storage="_MailingGeo3" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="EnableMailingAddress" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NameNoDiacritics" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Autonum" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DOBYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="People_Donation" Member="Donations" ThisKey="ID" OtherKey="PeopleID" Type="Donation" />
      <Association Name="People_Order" Member="Orders" ThisKey="ID" OtherKey="PeopleID" Type="Order" />
      <Association Name="Geo_People" Member="MailingGeo1" Storage="_Geo" ThisKey="MailingGeoID1" OtherKey="ID" Type="Geo" IsForeignKey="true" />
      <Association Name="Geo_People1" Member="MailingGeo2" Storage="_Geo1" ThisKey="MailingGeoID2" OtherKey="ID" Type="Geo" IsForeignKey="true" />
      <Association Name="Geo_People2" Member="MailingGeo3" Storage="_Geo2" ThisKey="MailingGeoID3" OtherKey="ID" Type="Geo" IsForeignKey="true" />
      <Association Name="Geo_People3" Member="ResidentGeo1" Storage="_Geo3" ThisKey="ResidentGeoID1" OtherKey="ID" Type="Geo" IsForeignKey="true" />
      <Association Name="Geo_People4" Member="ResidentGeo2" Storage="_Geo4" ThisKey="ResidentGeoID2" OtherKey="ID" Type="Geo" IsForeignKey="true" />
      <Association Name="Geo_People5" Member="ResidentGeo3" Storage="_Geo5" ThisKey="ResidentGeoID3" OtherKey="ID" Type="Geo" IsForeignKey="true" />
      <Association Name="Sex_People" Member="Sex" ThisKey="SexID" OtherKey="ID" Type="Sex" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Org" Member="Orgs">
    <Type Name="Org">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NameNoDiacritics" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GeoID1" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GeoID2" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GeoID3" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Org_Campaign" Member="CampaignsByCoopOrg" ThisKey="ID" OtherKey="CoopOrgID" Type="Campaign" />
      <Association Name="Org_Campaign1" Member="CampaignsByHostOrg" ThisKey="ID" OtherKey="HostOrgID" Type="Campaign" />
      <Association Name="Org_Order" Member="Orders" ThisKey="ID" OtherKey="OrgID" Type="Order" />
      <Association Name="Geo_Org" Member="Geo1" ThisKey="GeoID1" OtherKey="ID" Type="Geo" IsForeignKey="true" />
      <Association Name="Geo_Org1" Member="Geo2" ThisKey="GeoID2" OtherKey="ID" Type="Geo" IsForeignKey="true" />
      <Association Name="Geo_Org2" Member="Geo3" ThisKey="GeoID3" OtherKey="ID" Type="Geo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Campaign" Member="Campaigns">
    <Type Name="Campaign">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ContactPhone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SourceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="Campaign.StatusX" DbType="Int" CanBeNull="true" />
      <Column Name="Est" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CoopOrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HostOrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NameNoDiacritics" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Type" Type="Campaign.TypeX" DbType="Int" CanBeNull="true" />
      <Association Name="Campaign_CampaignStatusHistory" Member="CampaignStatusHistories" ThisKey="ID" OtherKey="CampaignID" Type="CampaignStatusHistory" />
      <Association Name="Campaign_Donation" Member="Donations" ThisKey="ID" OtherKey="CampaignID" Type="Donation" />
      <Association Name="Org_Campaign" Member="CoopOrg" ThisKey="CoopOrgID" OtherKey="ID" Type="Org" IsForeignKey="true" />
      <Association Name="Org_Campaign1" Member="HostOrg" ThisKey="HostOrgID" OtherKey="ID" Type="Org" IsForeignKey="true" />
      <Association Name="TestDef_Campaign" Member="Source" ThisKey="SourceID" OtherKey="ID" Type="TestDef" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CampaignStatusHistory" Member="CampaignStatusHistories">
    <Type Name="CampaignStatusHistory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CampaignID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FromStatus" Type="Campaign.StatusX" DbType="Int" CanBeNull="true" />
      <Column Name="ToStatus" Type="Campaign.StatusX" DbType="Int" CanBeNull="true" />
      <Column Name="Actor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Campaign_CampaignStatusHistory" Member="Campaign" ThisKey="CampaignID" OtherKey="ID" Type="Campaign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Excel" Member="Excels">
    <Type Name="Excel">
      <Column Name="STT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MSTM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MSNH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HoVaTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DOB" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ABO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HIV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HBsAg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HCV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Syphilis" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Malaria" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CampaignID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Imported" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SideEffect" Member="SideEffects">
    <Type Name="SideEffect">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FullnameNoDiacritics" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="SideEffect_SideEffect" Member="ChildSideEffects" Storage="_SideEffects" ThisKey="ID" OtherKey="ParentID" Type="SideEffect" />
      <Association Name="SideEffect_PackSideEffect" Member="PackSideEffects1" ThisKey="ID" OtherKey="SideEffectID1" Type="PackSideEffect" />
      <Association Name="SideEffect_PackSideEffect1" Member="PackSideEffects2" ThisKey="ID" OtherKey="SideEffectID2" Type="PackSideEffect" />
      <Association Name="SideEffect_PackSideEffect2" Member="PackSideEffects3" ThisKey="ID" OtherKey="SideEffectID3" Type="PackSideEffect" />
      <Association Name="SideEffect_SideEffect" Member="ParentSideEffect" Storage="_SideEffect1" ThisKey="ParentID" OtherKey="ID" Type="SideEffect" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PackSideEffect" Member="PackSideEffects">
    <Type Name="PackSideEffect">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SideEffectID1" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SideEffectID2" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SideEffectID3" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PackID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Actor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SideEffect_PackSideEffect" Member="SideEffect1" ThisKey="SideEffectID1" OtherKey="ID" Type="SideEffect" IsForeignKey="true" />
      <Association Name="SideEffect_PackSideEffect1" Member="SideEffect2" ThisKey="SideEffectID2" OtherKey="ID" Type="SideEffect" IsForeignKey="true" />
      <Association Name="SideEffect_PackSideEffect2" Member="SideEffect3" ThisKey="SideEffectID3" OtherKey="ID" Type="SideEffect" IsForeignKey="true" />
      <Association Name="Pack_PackSideEffect" Member="Pack" ThisKey="PackID" OtherKey="ID" Type="Pack" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FullnameNoDiacritics" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HospitalID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Department_Department" Member="ChildDepartments" ThisKey="ID" OtherKey="ParentID" Type="Department" />
      <Association Name="Department_Order" Member="OrdersByDepartment1" ThisKey="ID" OtherKey="DepartmentID1" Type="Order" />
      <Association Name="Department_Order1" Member="OrdersByDepartment2" ThisKey="ID" OtherKey="DepartmentID2" Type="Order" />
      <Association Name="Department_Order2" Member="OrdersByDepartment3" ThisKey="ID" OtherKey="DepartmentID3" Type="Order" />
      <Association Name="Department_Department" Member="ParentDepartment" ThisKey="ParentID" OtherKey="ID" Type="Department" IsForeignKey="true" />
      <Association Name="Hospital_Department" Member="Hospital" ThisKey="HospitalID" OtherKey="ID" Type="Hospital" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Facility" Member="Facilities">
    <Type Name="Facility">
      <Column Name="FIN" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CountingYY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CountingNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ST_General" Member="ST_Generals">
    <Type Name="ST_General">
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RetiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ST_General_Donation" Member="Donations" ThisKey="Code" OtherKey="ST010Code" Type="Donation" />
    </Type>
  </Table>
  <Table Name="dbo.DonationStatusLog" Member="DonationStatusLogs">
    <Type Name="DonationStatusLog">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DIN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FromStatus" Type="Donation.StatusX" DbType="Int" CanBeNull="true" />
      <Column Name="ToStatus" Type="Donation.StatusX" DbType="Int" CanBeNull="true" />
      <Column Name="Actor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Donation_DonationStatusLog" Member="Donation" ThisKey="DIN" OtherKey="DIN" Type="Donation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Donation" Member="Donations">
    <Type Name="Donation">
      <Column Name="DIN" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CheckChar" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CollectedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="Donation.StatusX" DbType="Int" CanBeNull="true" />
      <Column Name="PeopleID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Actor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CampaignID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MSTM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MSNH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BloodGroup" Storage="_ABORhD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ST010Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ST011" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ST012" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ST013" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ST014" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ST015" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ST016" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InfectiousMarkers" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OrgPackID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TestResultStatus" Type="Donation.TestResultStatusX" DbType="Int" CanBeNull="true" />
      <Column Name="Collector" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Donation_DonationStatusLog" Member="DonationStatusLogs" ThisKey="DIN" OtherKey="DIN" Type="DonationStatusLog" />
      <Association Name="Donation_DonationTestLog" Member="DonationTestLogs" ThisKey="DIN" OtherKey="DIN" Type="DonationTestLog" />
      <Association Name="Donation_Pack" Member="Packs" ThisKey="DIN" OtherKey="DIN" Type="Pack" />
      <Association Name="People_Donation" Member="People" ThisKey="PeopleID" OtherKey="ID" Type="People" IsForeignKey="true" />
      <Association Name="ST_General_Donation" Member="ST_General" ThisKey="ST010Code" OtherKey="Code" Type="ST_General" IsForeignKey="true" />
      <Association Name="Campaign_Donation" Member="Campaign" ThisKey="CampaignID" OtherKey="ID" Type="Campaign" IsForeignKey="true" />
      <Association Name="Pack_Donation" Member="Pack" ThisKey="OrgPackID" OtherKey="ID" Type="Pack" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.DonationTestLog" Member="DonationTestLogs">
    <Type Name="DonationTestLog">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DIN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Result" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Actor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Donation_DonationTestLog" Member="Donation" ThisKey="DIN" OtherKey="DIN" Type="Donation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PeopleID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Actor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Type" Type="Order.TypeX" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="Order.StatusX" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentID1" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DepartmentID2" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DepartmentID3" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Room" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Bed" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Diagnosis" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PatientCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TransfusionNote" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Order_PackOrder" Member="PackOrders" ThisKey="ID" OtherKey="OrderID" Type="PackOrder" />
      <Association Name="Department_Order" Member="Department1" ThisKey="DepartmentID1" OtherKey="ID" Type="Department" IsForeignKey="true" />
      <Association Name="Department_Order1" Member="Department2" ThisKey="DepartmentID2" OtherKey="ID" Type="Department" IsForeignKey="true" />
      <Association Name="Department_Order2" Member="Department3" ThisKey="DepartmentID3" OtherKey="ID" Type="Department" IsForeignKey="true" />
      <Association Name="Org_Order" Member="Org" ThisKey="OrgID" OtherKey="ID" Type="Org" IsForeignKey="true" />
      <Association Name="People_Order" Member="People" ThisKey="PeopleID" OtherKey="ID" Type="People" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StoreFinalize" Member="StoreFinalizes">
    <Type Name="StoreFinalize">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Type" Type="PackTransaction.TypeX" DbType="Int" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PackRemainDaily" Member="PackRemainDailies">
    <Type Name="PackRemainDaily">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PackID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="Pack.StatusX" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Pack_PackRemainDaily" Member="Pack" ThisKey="PackID" OtherKey="ID" Type="Pack" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RetiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Duration" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OriginalVolume" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StoredTemperature" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdditiveSolution" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LabelDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Product_ReceiptProduct" Member="ReceiptProducts" ThisKey="Code" OtherKey="ProductCode" Type="ReceiptProduct" />
      <Association Name="Product_Pack" Member="Packs" ThisKey="Code" OtherKey="ProductCode" Type="Pack" />
    </Type>
  </Table>
  <Table Name="dbo.Receipt" Member="Receipts">
    <Type Name="Receipt">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Receipt_ReceiptProduct" Member="ReceiptProducts" ThisKey="ID" OtherKey="ReceiptID" Type="ReceiptProduct" />
    </Type>
  </Table>
  <Table Name="dbo.ReceiptProduct" Member="ReceiptProducts">
    <Type Name="ReceiptProduct">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiptID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="ReceiptProduct.TypeX" DbType="Int" CanBeNull="true" />
      <Association Name="Product_ReceiptProduct" Member="Product" ThisKey="ProductCode" OtherKey="Code" Type="Product" IsForeignKey="true" />
      <Association Name="Receipt_ReceiptProduct" Member="Receipt" ThisKey="ReceiptID" OtherKey="ID" Type="Receipt" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Log]" Member="Logs">
    <Type Name="Log">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Method" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Actor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" AutoSync="OnInsert" Type="System.DateTime" DbType="DateTime" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="Log.StatusX" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_ProductCount" Member="vw_ProductCounts">
    <Type Name="vw_ProductCount">
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="Pack.StatusX" DbType="Int" CanBeNull="true" />
      <Column Name="BloodGroup" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TestResultStatus" Type="Donation.TestResultStatusX" DbType="Int" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Volume" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_PackRemainDaily" Member="vw_PackRemainDailies">
    <Type Name="vw_PackRemainDaily">
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BloodGroup" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Volume" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_PackTrans" Member="vw_PackTrans">
    <Type Name="vw_PackTran">
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BloodGroup" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Type" Type="PackTransaction.TypeX" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Volume" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Return]" Member="Returns">
    <Type Name="Return">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" AutoSync="OnInsert" Type="System.DateTime" DbType="DateTime" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="Actor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Return_PackOrder" Member="PackOrders" ThisKey="ID" OtherKey="ReturnID" Type="PackOrder" />
    </Type>
  </Table>
  <Table Name="dbo.PackTransaction" Member="PackTransactions">
    <Type Name="PackTransaction">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PackID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Type" Type="PackTransaction.TypeX" DbType="Int" CanBeNull="true" />
      <Column Name="Date" AutoSync="OnInsert" Type="System.DateTime" DbType="DateTime" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FromStatus" Type="Pack.StatusX" DbType="Int" CanBeNull="true" />
      <Column Name="ToStatus" Type="Pack.StatusX" DbType="Int" CanBeNull="true" />
      <Column Name="Actor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Pack_PackTransaction" Member="Pack" ThisKey="PackID" OtherKey="ID" Type="Pack" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PackOrder" Member="PackOrders">
    <Type Name="PackOrder">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PackID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReturnID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_PackOrder" Member="Order" ThisKey="OrderID" OtherKey="ID" Type="Order" IsForeignKey="true" />
      <Association Name="Return_PackOrder" Member="Return" ThisKey="ReturnID" OtherKey="ID" Type="Return" IsForeignKey="true" />
      <Association Name="Pack_PackOrder" Member="Pack" ThisKey="PackID" OtherKey="ID" Type="Pack" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PrintSetting" Member="PrintSettings">
    <Type Name="PrintSetting">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Top]" Member="Top" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Left]" Member="Left" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Font" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Width" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Height" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Delete]" Member="Deletes">
    <Type Name="Delete">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" AutoSync="OnInsert" Type="System.DateTime" DbType="DateTime" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="Actor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Delete_Pack" Member="Packs" ThisKey="ID" OtherKey="DeleteID" Type="Pack" />
    </Type>
  </Table>
  <Table Name="dbo.Pack" Member="Packs">
    <Type Name="Pack">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DIN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" AutoSync="OnInsert" Type="System.DateTime" DbType="DateTime" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Actor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Volume" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="Pack.StatusX" DbType="Int" CanBeNull="true" />
      <Column Name="DeleteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Pack_PackSideEffect" Member="PackSideEffects" ThisKey="ID" OtherKey="PackID" Type="PackSideEffect" />
      <Association Name="Pack_Donation" Member="Donations" ThisKey="ID" OtherKey="OrgPackID" Type="Donation" />
      <Association Name="Pack_PackRemainDaily" Member="PackRemainDailies" ThisKey="ID" OtherKey="PackID" Type="PackRemainDaily" />
      <Association Name="Pack_PackTransaction" Member="PackTransactions" ThisKey="ID" OtherKey="PackID" Type="PackTransaction" />
      <Association Name="Pack_PackOrder" Member="PackOrders" ThisKey="ID" OtherKey="PackID" Type="PackOrder" />
      <Association Name="Delete_Pack" Member="Delete" ThisKey="DeleteID" OtherKey="ID" Type="Delete" IsForeignKey="true" />
      <Association Name="Donation_Pack" Member="Donation" ThisKey="DIN" OtherKey="DIN" Type="Donation" IsForeignKey="true" />
      <Association Name="Product_Pack" Member="Product" ThisKey="ProductCode" OtherKey="Code" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
</Database>