//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string AddPoint {
            get {
                return ResourceManager.GetString("AddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu..
        /// </summary>
        internal static string EmptyDataText {
            get {
                return ResourceManager.GetString("EmptyDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phó Giám Đốc.
        /// </summary>
        internal static string FooterLine1 {
            get {
                return ResourceManager.GetString("FooterLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cộng Hòa Xã Hội Chủ Nghĩa Việt Nam.
        /// </summary>
        internal static string HdrLine1 {
            get {
                return ResourceManager.GetString("HdrLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độc lập - Tự do - Hạnh phúc.
        /// </summary>
        internal static string HdrLine2 {
            get {
                return ResourceManager.GetString("HdrLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh viện Chợ Rẫy.
        /// </summary>
        internal static string HdrLine3 {
            get {
                return ResourceManager.GetString("HdrLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trung tâm Truyền máu Chợ Rẫy.
        /// </summary>
        internal static string HdrLine4 {
            get {
                return ResourceManager.GetString("HdrLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa.
        /// </summary>
        internal static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu máu và sản xuất bởi.
        /// </summary>
        internal static string OrgLine1 {
            get {
                return ResourceManager.GetString("OrgLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trung tâm Truyền máu BV Chợ Rẫy.
        /// </summary>
        internal static string OrgLine2 {
            get {
                return ResourceManager.GetString("OrgLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh viện Chợ Rẫy.
        /// </summary>
        internal static string OrgLine3 {
            get {
                return ResourceManager.GetString("OrgLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tp Hồ Chí Minh, Việt Nam.
        /// </summary>
        internal static string OrgLine4 {
            get {
                return ResourceManager.GetString("OrgLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu..
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở khóa.
        /// </summary>
        internal static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
