<?xml version="1.0" encoding="utf-8"?><Database Name="RedBlood_DB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\RedBlood_DB.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RedBlood_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Campaign" Member="Campaign1s">
    <Type Name="Campaign1">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NameNoDiacritics" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ContactPhone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SourceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Est" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CoopOrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HostOrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>